// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVVvqX3ktJSZpqsmN91hsfLDJ2zKMpxig',
    appId: '1:829774053674:android:931099b44b113d18b59e53',
    messagingSenderId: '829774053674',
    projectId: 'ws-mp-kodepedia',
    databaseURL: 'https://ws-mp-kodepedia-default-rtdb.firebaseio.com',
    storageBucket: 'ws-mp-kodepedia.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD92Ec2a_GP5fQoBY79DJGRttFclhXBQR0',
    appId: '1:829774053674:ios:7bb9783a3f3f9025b59e53',
    messagingSenderId: '829774053674',
    projectId: 'ws-mp-kodepedia',
    databaseURL: 'https://ws-mp-kodepedia-default-rtdb.firebaseio.com',
    storageBucket: 'ws-mp-kodepedia.firebasestorage.app',
    iosBundleId: 'com.megaplug.app',
  );

}